service:
  name: fin-flash

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev

functions:
  hello:
    handler: server/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - cors: true
